name: publish
on:
  release:
    types:
      - published # release, pre-release or draft is published
jobs:
  build-pack-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@getbreathelife'

      - run: yarn
      - run: |
          [[ "${{ github.event.release.prerelease }}" == "true" ]] && release_tag="next" || release_tag="latest"
          yarn publish --tag "$release_tag" --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
